[project]
name = "multiagent-inventory-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = [
    "ipykernel>=6.30.1",
    "pydantic-ai>=1.0.15",
    "python-dotenv>=1.1.1",
]
